services:
  mongodb:
    image: mongo:7
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  submission.api:
    image: submission.api
    build:
      context: .
      dockerfile: Submission.Api/Dockerfile
    networks:
      - app-network
    expose:
      - "8080"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=petition_database
      - PetitionSettings__AllowPetitionCreation=true

  nginx:
    image: petition-frontend
    build:
      context: .
      dockerfile: frontend-react/Dockerfile
    ports:
      - "9755:80"
    depends_on:
      - submission.api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
